name = "hexa-gavin-pub"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "hexagram-db"
database_id = "86b4edc6-b944-4ce1-9dbe-a1fb2a706782"
