// 学堂主题注册表(v3 §7.4)——学堂/「我的·研习」/全局搜索共用
export const LEARN_TOPICS = [
  {
    id: 'yinyang',
    to: '/basics/yinyang',
    title: '阴阳八卦',
    desc: '阴阳与爻、太极生八卦、八卦取象、先天后天方位图',
    time: '约 5 分钟',
    quiz: true,
    usedKeys: null,
  },
  {
    id: 'hetu-luoshu',
    to: '/basics/hetu-luoshu',
    title: '河图洛书',
    desc: '河图五行生成数、洛书九宫纵横之和，与先后天八卦的配属',
    time: '约 3 分钟',
    quiz: true,
    usedKeys: null,
  },
  {
    id: 'xiaoxi',
    to: '/basics/xiaoxi',
    title: '十二消息卦',
    desc: '阳息阴消十二辟卦，对应十二月与十二地支节气',
    time: '约 4 分钟',
    quiz: true,
    usedKeys: null,
  },
  {
    id: 'tuiyan',
    to: '/basics/tuiyan',
    title: '推演入门',
    desc: '起卦/本卦·动爻·变卦/六法分类/解卦流程——推演工作台总纲,新手先读这篇',
    time: '约 8 分钟',
    quiz: false,
    usedKeys: null,
  },
  {
    id: 'shicao',
    to: '/basics/shicao',
    title: '揲蓍成卦',
    desc: '大衍之数，三变成爻，六爻成卦——逐步演示古法起卦过程',
    time: '约 8 分钟',
    quiz: true,
    usedKeys: ['dayan'],
  },
  {
    id: 'meihua',
    to: '/basics/meihua',
    title: '梅花易数',
    desc: '观物起数：先天卦数、时间与数字起卦、体用断法',
    time: '约 6 分钟',
    quiz: true,
    usedKeys: ['meihua-time', 'meihua-number'],
  },
  {
    id: 'jinqian',
    to: '/basics/jinqian',
    title: '金钱卦',
    desc: '三枚铜钱六掷成卦，背三字二，最通行的简易起卦法',
    time: '约 4 分钟',
    quiz: true,
    usedKeys: ['jinqian'],
  },
  {
    id: 'guahua',
    to: '/basics/guahua',
    title: '六十四卦认读',
    desc: '看卦画认卦名、看卦名识卦画——错综与一爻之差的形近卦混在一起练',
    time: '约 5 分钟',
    quiz: true,
    usedKeys: null,
  },
  {
    id: 'yuanliu',
    to: '/basics/yuanliu',
    title: '易学源流',
    desc: '从伏羲画卦到程朱集成——易学三千年脉络与本站功能的出处地图',
    time: '约 5 分钟',
    quiz: false,
    usedKeys: null,
  },
  {
    id: 'shili',
    to: '/shili',
    title: '春秋筮例',
    desc: '左传/国语二十余条占筮与引易实录——现存最早的周易应用现场',
    time: '约 20 分钟',
    quiz: false,
    usedKeys: null,
  },
  {
    id: 'shishi',
    to: '/basics/shishi',
    title: '爻辞中的商周史事',
    desc: '王亥丧牛、高宗伐鬼方、帝乙归妹——藏在爻辞里的历史化石',
    time: '约 10 分钟',
    quiz: false,
    usedKeys: null,
  },
  {
    id: 'glossary',
    to: '/basics/glossary',
    title: '名词表',
    desc: '易学常用术语汇编：卦际关系、爻位、八宫纳甲、占法、图书',
    time: '随查随用',
    quiz: false,
    usedKeys: null,
  },
]

// 计算某主题的读/练/用状态(无该层则为 null)
export function topicStatus(topic, progress) {
  return {
    read: !!progress.read[topic.id],
    quiz: topic.quiz ? !!progress.quiz[topic.id]?.passed : null,
    used: topic.usedKeys ? topic.usedKeys.some(k => progress.used[k]) : null,
  }
}
